backend: 
  name: git-gateway
  branch: master #Branch to update (optional, defualts to master)

#These lines should not be indented
media_folder: "public/images"
public_folder: "/images"


collections:
  - label: "Blog"
    name: "posts"
    folder: "posts"
    create: true,
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}